[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc --noEmit"]

[start]
cmd = "node --version && ./node_modules/.bin/tsx --version && npx prisma db push --skip-generate && ./node_modules/.bin/tsx src/index.ts"
